name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  uitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/ui_automation_framework
          path: ui_automation_framework
      - name: Install Dependencies
        run: npm install
        working-directory: ./api_automation_framework
      - name: Run UI Tests
        run: npx cypress run
        working-directory: ./ui_automation_framework

  apitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/api_automation_framework
          path: api_automation_framework
      - name: Install Dependencies
        run: npm install
        working-directory: ./api_automation_framework
      - name: Run API Tests
        run: npx cypress open
        working-directory: ./api_automation_framework
