name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  uitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/ui_automation_framework
          path: ui_automation_framework
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Run UI Tests
        run: npx cypress run

  apitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/api_automation_framework
          path: ui_automation_framework
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Run UI Tests
        run: npx cypress run
