name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  uitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/ui_automation_framework
          path: ui_automation_framework
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: ./ui_automation_framework
          wait-on: 'http://100.25.33.224:8000'

  apitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: euribes/api_automation_framework
          path: api_automation_framework
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: ./api_automation_framework
          wait-on: 'http://100.25.33.224:8000'
